function Deck(){

this.answerDeck = ['Being on Fire',
  'Racism',
  'Old-people smell',
  'A micropenis',
  'Women in yogurt commercials',
  'Classist undertones',
  'Not giving a shit about the Third World',
  'Inserting a mason jar into my anus',
  'Court-ordered rehab',
  'A windmill full of corpses',
  'The gays',
  'An oversized lollipop',
  'African children',
  'An asymmetric boob job',
  'Bingeing and purging',
  'The hardworking Mexican',
  'An Oedipus complex',
  'A tiny horse',
  'Boogers',
  'Penis envy',
  'Barrack Obama',
  'My humps',
  'The Tempuer-Pedic Swedish Sleep System',
  'Scientology',
  'Dry heaving',
  'Skeletor',
  'Darth Vader',
  'Figgy pudding',
  'Advice from a wise, old black man',
  'Five-Dollar Footlongs',
  'Elderly Japanese men',
  'Free samples',
  'Estrogen',
  'Sexual tension',
  'Famine',
  'A stray pube',
  'Men',
  'Heartwarming orphans',
  'Chunks of dead hitchhiker',
  'A bag of magic beans',
  'Repression',
  'Prancing',
  'My relationship status',
  'Overcompensation',
  'Peeing a little bit',
  'Pooping back and forth Forever',
  'A ball of earwax, semen, and toenail clippings',
  'Testicular torsion',
  'The Devil himself',
  'The World of Warcraft',
  'Dick Cheney',
  'MichaHitler',
  'Being fabulous',
  'Pictures of Boobs',
  'A gentle caress of the inner thigh',
  'The Amish',
  'the rhythms of Africa',
  'Lance Armstrong\'s missing testicle',
  'Pedophiles',
  'The Pope',
  'Flying sex snakes',
  'Sarah Palin',
  'Feeding Rosie O\'Donnell',
  'Sexy pillow fights',
  'Invading Poland',
  'Cybernetic enhancements',
  'Civilian casualties',
  'Jobs',
  'The female orgasm',
  'Bitches',
  'The Boy Scouts of America',
  'Auschwitz',
  'Finger painting',
  'The Care Bear Stare',
  'The Jews',
  'Being marginalized',
  'The Blood of Christ',
  'Dead parents',
  'The art of seduction',
  'Dying of dysentery',
  'Mr Clean right behind you',
  'Magnets',
  'Jewish fraternities',
  'Hot Pockets',
  'Natalie Portman',
  'Agriculture',
  'Judge Judy',
  'Surprise sex!',
  'The homosexual agenda',
  'Robert Downey, Jr',
  'The Trail of Tears',
  'An M',
  ' Night Shyamalan plot twist',
  'Funky fresh rhymes',
  'The light of a billion suns',
  ' Amputees',
  'Throwing a virgin into a volcano',
  'Italians',
  'Explosions',
  'A good sniff',
  'Destroying the evidence'];

this.questionDeck = [ 'How did I lose my virginity?',
  'Why can’t I sleep at night?',
  'What’s that smell?',
  'I got 99 problems but 888 ain’t one.',
  'Maybe she’s born with it. Maybe it’s 888.',
  'What’s the next Happy Meal Toy?',
  'Here is the church, Here is the steeple, Open the doors, And there is 888.',
  'It’s a pity that kids these days are all getting involved with 888.',
  'Alternative medicine is now embracing the curative powers of 888.',
  'What’s that sound?',
  'What ended my last relationship?'];

}

module.exports = Deck;